import {
  LayoutDashboard,
  CalendarDays,
  ClipboardList,
  ClipboardCheck,
  Users,
  BedDouble,
  Ban,
  ArrowRightLeft,
  Sparkles,
  Wrench,
  IdCard,
  Clock,
  FileText,
  Wallet,
  Truck,
  BarChart3,
  Zap,
  Share2,
  Settings,
  Shield,
  Plus,
  Search,
  Bell,
  Moon,
  Languages,
  LogOut,
  LogIn,
  ChevronDown,
  Eye,
  EyeOff,
  Lock,
  User,
  Building2,
  X,
  Pencil,
  Check,
  Power,
  Mail,
  Phone,
  SlidersHorizontal,
  UserPlus,
  KeyRound,
  MoreVertical,
  AlertTriangle,
  Crown,
  ShieldCheck,
  ConciergeBell,
  Brush,
  ArrowUp,
  ArrowDown,
  Info,
  RotateCcw,
  Star,
  ChevronLeft,
  ChevronRight,
  Minus,
  Trash2,
  CircleSlash2,
  UsersRound,
  CalendarPlus,
  Link2,
  Baby,
  TrendingUp,
  TrendingDown,
  CreditCard,
  Copy,
  type LucideIcon,
} from "lucide-react";

// Single icon mapper (overview §3 / DECISIONS D3). Reference the glyph everywhere by
// its semantic name so swapping the icon set is a one-file change.
const ICONS = {
  dashboard: LayoutDashboard,
  calendar: CalendarDays,
  reservations: ClipboardList,
  guests: Users,
  rooms: BedDouble,
  "room-blocks": Ban,
  "bulk-update": ArrowRightLeft,
  cleaning: Sparkles,
  maintenance: Wrench,
  employees: IdCard,
  attendance: Clock,
  "my-requests": FileText,
  "approve-requests": ClipboardCheck,
  documents: FileText,
  finance: Wallet,
  "credit-card": CreditCard,
  suppliers: Truck,
  reports: BarChart3,
  automations: Zap,
  channels: Share2,
  settings: Settings,
  permissions: Shield,
  plus: Plus,
  search: Search,
  bell: Bell,
  moon: Moon,
  languages: Languages,
  logout: LogOut,
  login: LogIn,
  chevron: ChevronDown,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  user: User,
  building: Building2,
  close: X,
  edit: Pencil,
  check: Check,
  power: Power,
  mail: Mail,
  phone: Phone,
  filter: SlidersHorizontal,
  "user-plus": UserPlus,
  key: KeyRound,
  more: MoreVertical,
  warning: AlertTriangle,
  crown: Crown,
  "shield-check": ShieldCheck,
  concierge: ConciergeBell,
  brush: Brush,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  info: Info,
  refresh: RotateCcw,
  star: Star,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  minus: Minus,
  trash: Trash2,
  "circle-slash": CircleSlash2,
  "users-round": UsersRound,
  "calendar-plus": CalendarPlus,
  link: Link2,
  baby: Baby,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  copy: Copy,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  size = 20,
  strokeWidth = 1.8,
}: {
  name: IconName;
  className?: string;
  size?: number;
  strokeWidth?: number;
}) {
  const Glyph = ICONS[name];
  return (
    <Glyph
      className={className}
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden
    />
  );
}
